### ISSUE TITLE
Incorrect python used in entrypoint?

### ISSUE THREAD

**Issue by dhirschfeld** [QuantStack/mamba#13]
On win64 I installed `mamba` into a new `py37` environment but it looks like the `mamba.exe` is looking for some random hard-coded python rather that the one in `C:\Miniconda3\envs\mamba`:
```
 λ  mamba Fatal error in launcher: Unable to create process using '"c:\bld\mamba_1553594356374\_h_env\python.exe"  "C:\Miniconda3\envs\mamba\Scripts\mamba.exe" '
```

Note: I don't have a `C:\bld` folder on my computer

**Comment by dhirschfeld** [comment]
The `mamba.exe` looks to contain a `__main__.py` file:

![image](https://user-images.githubusercontent.com/881019/55050318-c2364400-509b-11e9-9ec2-34c8b0c4ac09.png)

...with the below contents:
```python
# -*- coding: utf-8 -*-
import re
import sys

from mamba.mamba import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by dhirschfeld** [comment]
Fixed (for now) with the help of a `mamba.cmd` file:
```batch
%~dp0..\python.exe %~dp0mamba-script.py %*
```

**Comment by wolfv** [comment]
Could you review our setup.py & recipe?

We're setting the entry point like this:

https://github.com/QuantStack/mamba/blob/c301773da5e4d9fe6145de796b70936ea69cf2e9/setup.py#L97-L112

Do you know if we need to add `entry_points` to the meta.yaml in the recipe? We currently don't have that but I saw it in some other recipes.
This is our current version: https://github.com/conda-forge/mamba-feedstock/blob/master/recipe/meta.yaml

Btw I do believe that showing that it works fine on all three major platforms is really important, since that's one of the big selling points of Conda + what makes it so great.

**Comment by dhirschfeld** [comment]
IIUC entrypoints have to be explicitly specified also in the `meta.yaml`:
https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html?highlight=selectors#python-entry-points

I recently [fell afoul of this](https://github.com/conda-forge/staged-recipes/pull/8042#issuecomment-476146171) but conda threw an [error](https://github.com/conda/conda-build/blob/e8b076cc76ebaad40f6770664d265ecc22cfd99b/conda_build/noarch_python.py#L33) in my particular case.
