### ISSUE TITLE
Use a real thread when decompressing

### ISSUE THREAD

**Issue by wolfv** [QuantStack/mamba#138]
Right now, decompressing happens in the finalize callback in the main thread. 

This pauses the progress bar for a couple of seconds and I am also not sure what happens to the sockets that libcurl is downloading with. 

So we should have another thread that get's a queue of files to decompress.

**Comment by wolfv** [comment]
working on this now :)

**Comment by wolfv** [comment]
we have one secondary thread for decompression now. 

Multi-threaded doesn't appear to work well with libarchive, but it's also not really the bottleneck (downloading is slower then compression I think).
One could spawn some child processes for the decompression (instead of threads) in order to make libarchive work.

**Comment by NegatioN** [comment]
I would like to mention that compression seems to be a bottleneck if there's several packages that are large and need decompression in the same statement. They seem to be quicker if executed in sequence for example.

example slow install took `2m9s`: `mamba create -y -n test -c anaconda -c defaults -c conda-forge python=3.6 numpy==1.18.* pip==20.0.2 nomkl==3.0 pandas==1.0.* pillow==6.2.0 python-confluent-kafka==1.1.0 scipy==1.3.1 ipykernel==5.1.2 pylint==2.4.3 psutil==5.6.7 google-cloud-sdk==274.0.1 tqdm==4.47.* prometheus_client==0.3.0 fire==0.3.* cudatoolkit==9.0 cudnn==7.6 gensim==3.8.0`

(ran `conda remove -n test --all -y && conda clean -afy && rm -rf ~/.cache/` in between to hopefully get same conditions)

Example quicker install took `58.8s+12.5s`: `mamba create -y -n test -c anaconda -c defaults -c conda-forge python=3.6 numpy==1.18.* pip==20.0.2 nomkl==3.0 pandas==1.0.* pillow==6.2.0 python-confluent-kafka==1.1.0 scipy==1.3.1 ipykernel==5.1.2 pylint==2.4.3 psutil==5.6.7 google-cloud-sdk==274.0.1 tqdm==4.47.* prometheus_client==0.3.0 fire==0.3.* && mamba install -y -n test cudatoolkit==9.0 gensim==3.8.0 cudnn==7.6`

If there's anything that can be done, I'm sure loads of deployments could benefit from this. I don't know if this is entirely due to the decompression stage, but it seems like it gets stuck there a lot @wolfv
