### ISSUE TITLE
mamba install channel1::pkg doesn't work when channel2::pkg is installed

### ISSUE THREAD

**Issue by isuruf** [QuantStack/mamba#38]

**Comment by wolfv** [comment]
I just tested with 

`mamba install xtensor -c quantstack` where quantstacks has `xtensor` version `0.11.3`.
Indeed, as you say, it will not install xtensor anew. 

However, when I specify explicitly the version it works; `mamba install xtensor==0.11.3 -c quantstack` 

So I guess that might be a workaround for the moment. I am actually not sure what the correct behavior is in this case, but I guess emulating conda makes sense. I just don't know how for the moment.

**Comment by dhirschfeld** [comment]
I'd be fine with:
```
mamba install xtensor -c quantstack
```
...not installing `quantstack::xtensor=0.11.3` if `conda-forge::xtensor=0.11.3` was already installed.

However if I wrote:
```
mamba install quantstack::xtensor -c quantstack
```
...I'd want it to replace my `conda-forge::xtensor=0.11.3` with `quantstack::xtensor=0.11.3`

**Comment by wolfv** [comment]
We currenty still don't support the `channel::pkg` syntax (actually it's `channel:namespace:pkg`).

We will have to rework the logic in mamba and libsolv slightly to make it possible.

**Comment by wolfv** [comment]
Just to give more details on what's necessary for this to work:

- we need to change our usage of `conda_build_form` to make sure that it does _not_ remove the channel attribute. We could either implement this transformation on the C++ side or copy the necessary Python bits to do this in mamba
- change the libsolv code that does sorting of the packages by version to disregard any that do not come from the desired channel

**Comment by wolfv** [comment]
I think this work can be important to later also support namespaces in mamba

**Comment by dhirschfeld** [comment]
Not sure if you're in the business of fixing conda problems but the channel syntax functionality would be greatly improved if you could allow a channel only for the specified package without letting the solver use that channel for other packages.

e.g. specifying `mamba install quantstack::xtensor`  without having to add `quantstack` to the channel list

***xref:*** https://github.com/conda/conda/issues/9091

The lack of this functionality has caused `conda-forge` to have to create `rc` channels for each and every package... which was the same workaround we arrived at internally.

**Comment by wolfv** [comment]
I can totally see how this would be very nice for beta channels etc.
I think the best idea here would be to force the usage of `channel::pkg`, and add `channel` as the lowest-priority channel to the mix so that if the other channels can't satisfy some e.g. beta dependency, it will be taken from the beta-channel (or broken channel etc).
It should be quite straightforward to do this. Maybe we should hide it behind a flag ...

Another thing I noticed is that afaik the `channel::pkg` syntax is not allowed in the meta.yaml file?

**Comment by wolfv** [comment]
btw we have strict prio in mamba as well now :)

**Comment by dhirschfeld** [comment]
> Another thing I noticed is that afaik the channel::pkg syntax is not allowed in the meta.yaml file?

Yeah, that has been a bit of an issue for us too because of our workflow which relies on *not* using strict channel priority. We have `prod`, `uat`, and `dev` channels in that order. Normal users only have access to `prod`, developers have access to all 3 channels.

The idea is that a developer can update to the latest master build simply by doing a `conda update pkg`. Because we *don't* use strict channel priority this will update the `prod` package from the lower `dev` channel because the package in `dev` has the higher version number.

i.e. the workflow relies on updates picking the latest version of a package on *any* of the available channels with governance enforced by limiting access to the individual channels.

...in case you wanted to know ;)


This does actually work since by-and-large conda-forge and defaults *are* actually compatible. I think these days `qt` is the only problem package.

**Comment by wolfv** [comment]
@dhirschfeld we have implemented support for the `quantstack::breathe` syntax in mamba now (will be released today).

It follows the following rule: the quantstack channel is added as the lowest priority repo to the channels, and the specific packages are hoisted into a special "override" repo with highest (strict) prio. The solver can still reach into the quantstack repo if some other package doesn't exist in e.g. conda-forge, but wouldn't do that if it does.

Using --strict-priority with this feature should further override packages from e.g. quantstack with conda-forge.

**Comment by wolfv** [comment]
note: we still don't support to automatically switch channels. I think this could be a reasonable feature when specifying channels hard coded. 

I also want to support channel switching better when running a `update --all`. 

In all other cases mamba will be less agressive about channel switching (`update --all` will trigger a new solve for all explicitly installed specs, and thus also switch channels to the new config).

**Comment by wolfv** [comment]
the channel-specific selection is implemented in a different way now and will properly override any other installed package.
