### ISSUE TITLE
Install pip with python

### ISSUE THREAD

**Issue by isuruf** [QuantStack/mamba#85]
conda installs pip with python if `add_pip_as_python_dependency` is not set to False.

**Comment by wolfv** [comment]
thanks for opening these issues, it's very useful :)

**Comment by wolfv** [comment]
So, adding pip to a direct installation of Python is actually easy, but adding pip the way conda does is kinda tricky -- because they are straight away editing the repodata to add pip as run time dependency of Python. Not sure what to do with this. 

We could either do what conda does and edit the metadata which would be potentially slow or we could do a two-stage solve process where in the first stage we solve the original problem, then detect if `python` is going to be installed, and then we add pip as into the original mix (this option seems much cleaner and faster).

**Comment by wolfv** [comment]
This is the code in conda which adds' pip and also takes care of legacy packages vs new style conda packages: 

https://github.com/conda/conda/blob/f4d8ae9f4577008deddf4eb8be52e0abbacf475a/conda/core/subdir_data.py#L402-L432

**Comment by isuruf** [comment]
Thanks
